### ISSUE TITLE
Key composed of only digits are not supported?

### ISSUE THREAD

**Issue by rkutin** [fbernier/tomlrb#1]
Hello,

Regarding spec of toml:
"Keys may be either bare or quoted. Bare keys may only contain letters, numbers, underscores, and dashes (A-Za-z0-9_-). Note that bare keys are allowed to be composed of only digits, e.g. 1234."

with following example:
[table]
1234 = "bare integer"

Library return an error:

> Tomlrb.parse("[table]\n1234 = \"bare integer\"")
> Tomlrb::ParseError:
> parse error on value "1234" (INTEGER)
>     from /Users/home/.rvm/gems/ruby-2.1.5/gems/tomlrb-1.1.1/lib/tomlrb.rb:19:in `rescue in parse'
>     from /Users/home/.rvm/gems/ruby-2.1.5/gems/tomlrb-1.1.1/lib/tomlrb.rb:16:in`parse'
>     from (irb):4
>     from /Users/home/.rvm/rubies/ruby-2.1.5/bin/irb:11:in `<main>'

Same when key name starts by number:

> Tomlrb.parse("[table]\n1234a = \"bare integer\"")
> Tomlrb::ParseError:
> parse error on value "1234" (INTEGER)
>     from /Users/home/.rvm/gems/ruby-2.1.5/gems/tomlrb-1.1.1/lib/tomlrb.rb:19:in `rescue in parse'
>     from /Users/home/.rvm/gems/ruby-2.1.5/gems/tomlrb-1.1.1/lib/tomlrb.rb:16:in`parse'
>     from (irb):6
>     from /Users/home/.rvm/rubies/ruby-2.1.5/bin/irb:11:in `<main>'

Same test with key name started by letter - works..

> Tomlrb.parse("[table]\na1234 = \"bare integer\"")
>  => {"table"=>{"a1234"=>"bare integer"}}

Regards,
Roman

**Comment by fbernier** [comment]
Thanks for the report, I had fallen on this issue in the past but forgot about it. I just pushed v1.1.3 (1.1.2 had been :disappointed: ) which should fix it.
