### ISSUE TITLE
integers can end in "_"s

### ISSUE THREAD

**Issue by sgarciac** [fbernier/tomlrb#11]
tomlrb chokes on this valid toml expression:

```
francois=45_
```

Please fix.

**Comment by fbernier** [comment]
Can you point me where this is defined in the spec?

**Comment by fbernier** [comment]
Found it. Not sure this need to be fixed so I asked: https://github.com/toml-lang/toml/pull/296#issuecomment-289800318

**Comment by fbernier** [comment]
Alright I'm closing this as "wontfix" https://github.com/toml-lang/toml/pull/296#issuecomment-289836499
