### ISSUE TITLE
parse error for literal string keys in tables

### ISSUE THREAD

**Issue by rampion** [fbernier/tomlrb#12]
The parser doesn't allow for literal string keys in tables, such as

```
[a.'cfg']
b = 1
```

For example:

```
2.1.5 :003 > Tomlrb.parse("[a.'cfg']\nb = 1")
Tomlrb::ParseError: 
parse error on value "cfg" (STRING_LITERAL)
        from /usr/local/rvm/gems/ruby-2.1.5/gems/tomlrb-1.2.3/lib/tomlrb.rb:25:in `rescue in parse'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/tomlrb-1.2.3/lib/tomlrb.rb:22:in `parse'
        from (irb):3
        from /usr/local/rvm/rubies/ruby-2.1.5/bin/irb:11:in `<main>'
2.1.5 :004 > Tomlrb.parse("[a.\"cfg\"]\nb = 1")
 => {"a"=>{"cfg"=>{"b"=>1}}} 
```

According to [the table spec](https://github.com/toml-lang/toml#user-content-table) "Naming rules for each dot separated part are the same as for keys (see definition of Key/Value Pairs).", and [the key/value pairs spec](https://github.com/toml-lang/toml#user-content-keyvalue-pair) explicitly allows literal strings - "Quoted keys follow the exact same rules as either basic strings or literal strings and allow you to use a much broader set of key names." and even gives one as an example (`'quoted "value"' = "value"`).

**Comment by rampion** [comment]
Rust's `time` crate already uses this (post 0.4.0) feature [in its `Cargo.toml` file](https://github.com/rust-lang-deprecated/time/blob/master/Cargo.toml#L18).

**Comment by fbernier** [comment]
Thanks for the report. I just pushed two commits to the master branch that should fix this. If you could let me know how that works for you I would appreciate it.

**Comment by rampion** [comment]
Works for me!

**Comment by fbernier** [comment]
`1.2.4` has been released to rubygems
