### ISSUE TITLE
Allow nested table names consisting of pure Integers (like [1.2])

### ISSUE THREAD

**Issue by Axel2** [fbernier/tomlrb#16]
[1.2] raises: 
parse error on value "1.2" (FLOAT)

**Comment by KitaitiMakoto** [comment]
@Axel2 Hi, I think #29 solved this issue. Could you try master branch?

**Comment by Axel2** [comment]
Hi, I did some short tests with master branch regarding this issue. Yes, it is solved now. I think, you can close it.

**Comment by KitaitiMakoto** [comment]
Thank you for confirmation!
