### ISSUE TITLE
Table/dict with false boolean values

### ISSUE THREAD

**Issue by jcarnu** [fbernier/tomlrb#23]
With the following toml structure, I get a  `<Tomlrb::ParseError: Unclosed table>` Error.

~~~toml
[test]
table=[
  {name='name1', visible=true},
  {name='name2', visible=false}
]
~~~

Here's the rb script 

~~~ruby
require "tomlrb"

testdata = Tomlrb.load_file("test.toml", symbolize_keys: true)
~~~

It turns out the `false` value makes the parser crash whereas if I change `false` to `true` value it does not.

If I have time to investigate further, I'll try to give some more information or a patch.

Thanks for your work, I use it everyday.

**Comment by fbernier** [comment]
Thanks for the report! Hard to believe this bug has been there for so long. It's fixed in https://github.com/fbernier/tomlrb/commit/14e7710d88b22b06dce746f572796d92ed6461e7 and released as 1.3.0 on rubygems.
