### ISSUE TITLE
FLOAT_INF error after updating to 1.3.0

### ISSUE THREAD

**Issue by evanleck** [fbernier/tomlrb#24]
Since updating to 1.3.0 I've started getting the error `parse error on value "inf" (FLOAT_INF)` which I assume is related to 4dd97667cd5654a9be0bfd651fc6c510c702e45d. 

I'm not familiar with how the scanner works but would a value of "info" trigger this? Maybe the regex for `FLOAT_INF` and `FLOAT_NAN` should have positional anchors or word boundary checks? Without a test for `FLOAT_INF` I'm not sure what the intended uses are.

I'm happy to put together a PR if that helps but I need a little guidance on what should be changed if you'd like me to do that.

Thanks!

**Comment by fbernier** [comment]
Hey, did you manage to extract a sample toml that causes the issue?

**Comment by evanleck** [comment]
You bet, this consistently causes the error for me:

```toml
[info]
this = "something"
```

Using this Ruby script to test:

```rb
require 'tomlrb'

loaded = Tomlrb.load_file('test.toml')
puts loaded.inspect
```

**Comment by fbernier** [comment]
Ah yes that's definitely an issue with the `inf`. Sorry for the trouble I'll check that out.

**Comment by mvangoor** [comment]
@fbernier kind reminder of this 'bug' and question if there might be a solution on the horizon ?
