### ISSUE TITLE
Which specific TOML 1.0.0 release candidate is supported?

### ISSUE THREAD

**Issue by marzer** [fbernier/tomlrb#38]
TOML isn't at `1.0.0` yet. It's still in the Release Candidate cycle, of which there have been three. This project advertises support for `1.0.0`, but which RC?

Consider updating the project's README to specify the specific RC version.

**Comment by KitaitiMakoto** [comment]
We use [iarna/toml-spec-tests](https://github.com/iarna/toml-spec-tests) with some modifications. Do you know which RC those tests conform to?

**Comment by marzer** [comment]
That repo was last updated 8 months ago, [around the same time](https://www.github.com/toml-lang/toml/tree/master/CHANGELOG.md) that RC 1 came out, so I suppose it's RC 1.

**Comment by marzer** [comment]
Although I see now your CHANGELOG.md says support for RC 3 was implemented...

**Comment by KitaitiMakoto** [comment]
yep, I need research with accuracy...

**Comment by KitaitiMakoto** [comment]
@marzer Sorry for taking log time. Now this gem conforms to 1.0.0.
refs: https://github.com/fbernier/tomlrb/pull/44

**Comment by marzer** [comment]
No worries. Congratulations!

**Comment by KitaitiMakoto** [comment]
Thanks!
