### ISSUE TITLE
why

### ISSUE THREAD

**Issue by ojej** [fbernier/tomlrb#43]
Why i cant use utf-8?

`wysokość = 90`

or name with dot

`[proste.jeden]`

**Comment by KitaitiMakoto** [comment]
TOML doesn't allow non-ASCII characters for key without quote: https://toml.io/en/v1.0.0#keys .
`"wysokość" = 90` can be parsed:

```ruby
Tomlrb.parse '"wysokość" = 90'
# => {"wysokość"=>90}
```

The same rule is also applied to table key:

```ruby
Tomlrb.parse '[parent."wysokość"]'
# => {"parent"=>{"wysokość"=>{}}}
```
