### ISSUE TITLE
Parser breaks on quoted key in inline table

### ISSUE THREAD

**Issue by katblag** [fbernier/tomlrb#47]
I'm trying to use this gem to parse TOML files from rustsec following an advisory [schema](https://github.com/rustsec/advisory-db#advisory-format) which includes an inline table using a quoted key like:
`functions = { "mycrate::MyType::vulnerable_function" = ["< 1.2.0, >= 1.1.0"] }`

The parser returns `Tomlrb::ParseError: parse error on value "mycrate::MyType::vulnerable_function" (STRING_BASIC)` when encountering this line.

It parses the inline table just fine without a quoted key like:
`functions = { vulnerable_function = ["< 1.2.0, >= 1.1.0"] }`

And also correctly parses a quoted key outside the inline table like:
`"functions" = { vulnerable_function = ["< 1.2.0, >= 1.1.0"] }`

So it seems to be specifically quoted keys _inside_ inline tables.

**Comment by fbernier** [comment]
Hey there,

I just tested with the changes in this PR: https://github.com/fbernier/tomlrb/pull/44 and it seems like it fixes your issue. We're working toward having it merged in and cutting a release not too soon after.

Thanks for reporting!

**Comment by KitaitiMakoto** [comment]
@katblag Now v2.0.2 should be able to parse it!

**Comment by katblag** [comment]
Verified our tests are now passing with the upgraded gem, thanks!
