### ISSUE TITLE
parse error on value "false" (FALSE)

### ISSUE THREAD

**Issue by StanBright** [fbernier/tomlrb#6]
Hi,

First, I'd like to thank you for working on tomlrb. It's helpful to all of us who have to parse .toml files. 

Second, I hit an exception today - **Tomlrb::ParseError - parse error on value "false" (FALSE)**. It can be reproduced by trying to parse this file: https://raw.githubusercontent.com/uutils/coreutils/master/Cargo.toml . 

Do you think that there's an easy fix to this?

**Comment by fbernier** [comment]
Thanks for the report. I'll have a look asap and let you know.

**Comment by fbernier** [comment]
I just released 1.2.3 with a fix for this. Let me know if that works for you. 🍻

**Comment by StanBright** [comment]
Cheers, mate 🍻! It worked as expected. 

Thanks a lot for the prompt response.
