### ISSUE TITLE
Parse error on value "cfg(target_os = \"macos\")" (STRING_LITERAL)

### ISSUE THREAD

**Issue by StanBright** [fbernier/tomlrb#7]
Hi @fbernier,

I just encountered an issue with parsing another file.

**The error is:**
parse error on value "cfg(target_os = \"macos\")" (STRING_LITERAL)

**You can find a sample file here:**
https://raw.githubusercontent.com/sfackler/rust-native-tls/master/Cargo.toml

Do you think it's easy to fix?

Thanks,
Stan

**Comment by fbernier** [comment]
Unfortunately that looks like something specific to Cargo to me (https://github.com/rust-lang/cargo/pull/2328) and not part of the TOML spec. See http://doc.crates.io/specifying-dependencies.html#platform-specific-dependencies.

If it's really a bug I'll be glad to fix it.

**Comment by StanBright** [comment]
Yeah, you are most probably right.

Anyway, thanks for responding so promptly!

In this case, maybe we should close this issue?

**Comment by fbernier** [comment]
Yes thanks for understanding. Cheers.
